import { Question } from './types';

const questionsPool: Record<string, Question[]> = {
  math: [
    { text: 'What is 2 + 2?', options: ['3', '4', '5', '6'], correct: 1 },
    { text: 'What is the square root of 16?', options: ['2', '4', '8', '16'], correct: 1 },
    { text: 'What is PI approximately?', options: ['2.14', '3.14', '4.14', '5.14'], correct: 1 },
    { text: 'What is 5 * 6?', options: ['30', '35', '40', '45'], correct: 0 },
    { text: 'What is the derivative of x^2?', options: ['x', '2x', 'x^2', '2'], correct: 1 },
    { text: 'What is sin(90°)?', options: ['0', '1', '-1', '0.5'], correct: 1 },
    { text: 'What is 10 / 2?', options: ['5', '6', '4', '3'], correct: 0 },
    { text: 'What is log10(100)?', options: ['1', '2', '3', '4'], correct: 1 },
    { text: 'What is the area of a circle?', options: ['πr', 'πr^2', '2πr', '2r'], correct: 1 },
    { text: 'What is 7^2?', options: ['49', '14', '21', '28'], correct: 0 },
  ],
  physics: [
    { text: 'What is the speed of light?', options: ['3x10^8 m/s', '3x10^6 m/s', '3x10^4 m/s', '3x10^2 m/s'], correct: 0 },
    { text: 'What is gravity on Earth?', options: ['9.8 m/s^2', '10 m/s^2', '8 m/s^2', '9 m/s^2'], correct: 0 },
    { text: 'What is Newton\'s first law?', options: ['Inertia', 'F=ma', 'Action-Reaction', 'Gravity'], correct: 0 },
    { text: 'What is the unit of force?', options: ['Newton', 'Joule', 'Watt', 'Pascal'], correct: 0 },
    { text: 'What is E=mc^2?', options: ['Mass-Energy', 'Kinetic Energy', 'Potential Energy', 'Momentum'], correct: 0 },
    { text: 'What is Ohm\'s law?', options: ['V=IR', 'P=IV', 'E=mc^2', 'F=ma'], correct: 0 },
    { text: 'What is the unit of power?', options: ['Watt', 'Joule', 'Newton', 'Ampere'], correct: 0 },
    { text: 'What is wave speed?', options: ['f * λ', 'f / λ', 'λ / f', 'f + λ'], correct: 0 },
    { text: 'What is kinetic energy?', options: ['1/2 mv^2', 'mg h', '1/2 k x^2', 'm v'], correct: 0 },
    { text: 'What is Coulomb\'s law?', options: ['F = k q1 q2 / r^2', 'F = m a', 'V = I R', 'E = m c^2'], correct: 0 },
  ],
  chemistry: [
    { text: 'What is H2O?', options: ['Water', 'Carbon Dioxide', 'Oxygen', 'Sodium Chloride'], correct: 0 },
    { text: 'What is the atomic number of Carbon?', options: ['6', '7', '8', '5'], correct: 0 },
    { text: 'What is pH of acid?', options: ['<7', '>7', '=7', '>14'], correct: 0 },
    { text: 'What is NaCl?', options: ['Salt', 'Sugar', 'Acid', 'Base'], correct: 0 },
    { text: 'What is Avogadro\'s number?', options: ['6.022x10^23', '3.14', '9.8', '1.6x10^-19'], correct: 0 },
    { text: 'What is a mole?', options: ['6.022x10^23 particles', '1 gram', '1 liter', '1 atom'], correct: 0 },
    { text: 'What is oxidation?', options: ['Loss of electrons', 'Gain of electrons', 'Loss of protons', 'Gain of protons'], correct: 0 },
    { text: 'From the periodic table, group 1 is?', options: ['Alkali metals', 'Halogens', 'Noble gases', 'Transition metals'], correct: 0 },
    { text: 'What is CH4?', options: ['Methane', 'Ethane', 'Propane', 'Butane'], correct: 0 },
    { text: 'What is electrolysis?', options: ['Decomposition by electricity', 'Synthesis by heat', 'Combustion', 'Fermentation'], correct: 0 },
  ],
  biology: [
    { text: 'What is photosynthesis?', options: ['Process in plants to make food', 'Breathing in animals', 'Digestion', 'Circulation'], correct: 0 },
    { text: 'What is DNA?', options: ['Deoxyribonucleic acid', 'Ribonucleic acid', 'Protein', 'Lipid'], correct: 0 },
    { text: 'What is the powerhouse of the cell?', options: ['Mitochondria', 'Nucleus', 'Ribosome', 'Golgi'], correct: 0 },
    { text: 'What is osmosis?', options: ['Diffusion of water', 'Diffusion of gas', 'Active transport', 'Phagocytosis'], correct: 0 },
    { text: 'What is natural selection?', options: ['Survival of fittest', 'Random mutation', 'Gene flow', 'Genetic drift'], correct: 0 },
    { text: 'What is the heart\'s function?', options: ['Pump blood', 'Digest food', 'Breathe', 'Think'], correct: 0 },
    { text: 'What is ecosystem?', options: ['Community and environment', 'Only animals', 'Only plants', 'Soil only'], correct: 0 },
    { text: 'What is mitosis?', options: ['Cell division', 'Meiosis', 'Fertilization', 'Mutation'], correct: 0 },
    { text: 'What is enzyme?', options: ['Biological catalyst', 'Hormone', 'Vitamin', 'Mineral'], correct: 0 },
    { text: 'What is biodiversity?', options: ['Variety of life', 'Single species', 'Extinction', 'Pollution'], correct: 0 },
  ],
  // New subjects with sample questions
  further_math: [
    { text: 'What is the integral of x dx?', options: ['x^2', 'x^2/2', '2x', 'ln x'], correct: 1 },
    { text: 'What is the determinant of [[1,2],[3,4]]?', options: ['-2', '2', '4', '1'], correct: 0 },
    { text: 'What is the sum of infinite GP 1 + 1/2 + 1/4 + ...?', options: ['1', '2', '3', 'Infinite'], correct: 1 },
    { text: 'What is cos(60°)?', options: ['0.5', '0', '1', '-0.5'], correct: 0 },
    { text: 'What is the binomial expansion of (a+b)^2?', options: ['a^2 + 2ab + b^2', 'a^2 + b^2', 'a^2 - 2ab + b^2', 'a + b'], correct: 0 },
    { text: 'What is the probability of rolling a 6 on a die?', options: ['1/6', '1/2', '1/3', '1/4'], correct: 0 },
    { text: 'What is the mean of 1,2,3?', options: ['2', '1', '3', '6'], correct: 0 },
    { text: 'What is vector dot product?', options: ['a.b = |a||b|cosθ', 'a.b = |a||b|sinθ', 'a x b', 'a / b'], correct: 0 },
    { text: 'What is the limit of (x^2 - 1)/(x-1) as x->1?', options: ['2', '1', '0', 'Undefined'], correct: 0 },
    { text: 'What is e^0?', options: ['1', '0', 'e', 'Undefined'], correct: 0 },
  ],
  agricultural_science: [
    { text: 'What is the main crop in Nigeria?', options: ['Cassava', 'Wheat', 'Rice', 'Corn'], correct: 0 },
    { text: 'What is soil erosion?', options: ['Loss of topsoil', 'Addition of soil', 'Plant growth', 'Animal farming'], correct: 0 },
    { text: 'What is a tractor used for?', options: ['Plowing', 'Cooking', 'Transport', 'Storage'], correct: 0 },
    { text: 'What is poultry?', options: ['Bird farming', 'Cattle farming', 'Fish farming', 'Crop farming'], correct: 0 },
    { text: 'What is fertilizer?', options: ['Nutrients for plants', 'Pesticide', 'Water', 'Seeds'], correct: 0 },
    { text: 'What is irrigation?', options: ['Artificial watering', 'Rain', 'Harvesting', 'Planting'], correct: 0 },
    { text: 'What is a greenhouse?', options: ['Controlled environment for plants', 'Animal shelter', 'Storage', 'Market'], correct: 0 },
    { text: 'What is crop rotation?', options: ['Changing crops to maintain soil', 'Same crop every year', 'Burning fields', 'Flooding'], correct: 0 },
    { text: 'What is beekeeping?', options: ['Apiculture', 'Sericulture', 'Pisciculture', 'Aquaculture'], correct: 0 },
    { text: 'What is pest control?', options: ['Managing harmful insects', 'Planting seeds', 'Harvesting', 'Selling'], correct: 0 },
  ],
  computer_studies: [
    { text: 'What is RAM?', options: ['Random Access Memory', 'Read Only Memory', 'Hard Drive', 'CPU'], correct: 0 },
    { text: 'What is a bit?', options: ['0 or 1', '8 bytes', '1024 bytes', 'Processor'], correct: 0 },
    { text: 'What is HTML?', options: ['HyperText Markup Language', 'Programming language', 'Database', 'OS'], correct: 0 },
    { text: 'What is a firewall?', options: ['Security system', 'Hardware', 'Software', 'Virus'], correct: 0 },
    { text: 'What is an algorithm?', options: ['Step by step procedure', 'Code', 'Data', 'Output'], correct: 0 },
    { text: 'What is binary for 2?', options: ['10', '01', '11', '00'], correct: 0 },
    { text: 'What is CPU?', options: ['Central Processing Unit', 'Memory', 'Screen', 'Keyboard'], correct: 0 },
    { text: 'What is internet?', options: ['Network of networks', 'Single computer', 'Software', 'Hardware'], correct: 0 },
    { text: 'What is a database?', options: ['Organized data', 'Code', 'Image', 'Video'], correct: 0 },
    { text: 'What is debugging?', options: ['Finding errors in code', 'Writing code', 'Running code', 'Deleting code'], correct: 0 },
  ],
  english: [
    { text: 'What is a synonym for happy?', options: ['Sad', 'Joyful', 'Angry', 'Tired'], correct: 1 },
    { text: 'What is the opposite of hot?', options: ['Cold', 'Warm', 'Boiling', 'Lukewarm'], correct: 0 },
    { text: 'What is a noun?', options: ['Person, place, thing', 'Action', 'Description', 'Connection'], correct: 0 },
    { text: 'What is alliteration?', options: ['Repetition of sounds', 'Rhyme', 'Metaphor', 'Simile'], correct: 0 },
    { text: 'From who wrote Romeo and Juliet?', options: ['Shakespeare', 'Dickens', 'Austen', 'Tolkien'], correct: 0 },
    { text: 'What is a verb?', options: ['Action word', 'Naming word', 'Describing word', 'Joining word'], correct: 0 },
    { text: 'What is metaphor?', options: ['Direct comparison', 'Like or as', 'Personification', 'Hyperbole'], correct: 0 },
    { text: 'What is punctuation?', options: ['Marks in writing', 'Spelling', 'Grammar', 'Vocabulary'], correct: 0 },
    { text: 'What is an adjective?', options: ['Describes noun', 'Action', 'Person', 'Place'], correct: 0 },
    { text: 'What is a sentence?', options: ['Complete thought', 'Word', 'Paragraph', 'Story'], correct: 0 },
  ],
  literature: [
    { text: 'Who wrote 1984?', options: ['Orwell', 'Huxley', 'Bradbury', 'Tolkien'], correct: 0 },
    { text: 'What is Hamlet?', options: ['Shakespeare play', 'Novel', 'Poem', 'Essay'], correct: 0 },
    { text: 'Who is Harry Potter author?', options: ['Rowling', 'Tolkien', 'Lewis', 'Martin'], correct: 0 },
    { text: 'What is To Kill a Mockingbird about?', options: ['Racism', 'War', 'Love', 'Adventure'], correct: 0 },
    { text: 'Who wrote Pride and Prejudice?', options: ['Austen', 'Bronte', 'Woolf', 'Shelley'], correct: 0 },
    { text: 'What is The Great Gatsby?', options: ['American dream', 'Fantasy', 'Horror', 'Sci-fi'], correct: 0 },
    { text: 'Who is Sherlock Holmes creator?', options: ['Doyle', 'Christie', 'Poe', 'King'], correct: 0 },
    { text: 'What is Moby Dick?', options: ['Whale hunt', 'Treasure hunt', 'Space travel', 'Detective'], correct: 0 },
    { text: 'Who wrote The Odyssey?', options: ['Homer', 'Virgil', 'Ovid', 'Sophocles'], correct: 0 },
    { text: 'What is Frankenstein?', options: ['Monster creation', 'Vampire', 'Ghost', 'Werewolf'], correct: 0 },
  ],
  government: [
    { text: 'What is the capital of Nigeria?', options: ['Lagos', 'Abuja', 'Kano', 'Ibadan'], correct: 1 },
    { text: 'Who is the current president of Nigeria?', options: ['Muhammadu Buhari', 'Bola Tinubu', 'Goodluck Jonathan', 'Olusegun Obasanjo'], correct: 1 },
    { text: 'What is the Nigerian legislature called?', options: ['National Assembly', 'Supreme Court', 'Senate', 'House'], correct: 0 },
    { text: 'What is democracy?', options: ['Government by the people', 'Rule by king', 'Military rule', 'Dictatorship'], correct: 0 },
    { text: 'What is the Nigerian currency?', options: ['Naira', 'Cedi', 'Rand', 'Shilling'], correct: 0 },
    { text: 'What is federalism?', options: ['Division of power', 'Central power', 'State power', 'Local power'], correct: 0 },
    { text: 'What is the Nigerian flag colors?', options: ['Green white green', 'Red black green', 'Blue white red', 'Yellow green blue'], correct: 0 },
    { text: 'What is the role of the judiciary?', options: ['Interpret laws', 'Make laws', 'Execute laws', 'Enforce laws'], correct: 0 },
    { text: 'What is a constitution?', options: ['Supreme law', 'Ordinary law', 'Custom', 'Tradition'], correct: 0 },
    { text: 'What is separation of powers?', options: ['Legislative, executive, judiciary', 'One branch', 'Two branches', 'Four branches'], correct: 0 },
  ],
  history: [
    { text: 'Who was the first US president?', options: ['Washington', 'Lincoln', 'Jefferson', 'Adams'], correct: 0 },
    { text: 'When was WWII?', options: ['1939-1945', '1914-1918', '1861-1865', '1776'], correct: 0 },
    { text: 'What is the capital of France?', options: ['Paris', 'Berlin', 'London', 'Madrid'], correct: 0 },
    { text: 'Who discovered America?', options: ['Columbus', 'Magellan', 'Cook', 'Vespucci'], correct: 0 },
    { text: 'What was the Renaissance?', options: ['Rebirth of art', 'Industrial revolution', 'French revolution', 'Civil war'], correct: 0 },
    { text: 'Who was Cleopatra?', options: ['Egyptian queen', 'Roman empress', 'Greek goddess', 'British monarch'], correct: 0 },
    { text: 'What is the Great Wall?', options: ['In China', 'In Rome', 'In Egypt', 'In India'], correct: 0 },
    { text: 'When was the moon landing?', options: ['1969', '1959', '1979', '1989'], correct: 0 },
    { text: 'Who was Martin Luther King?', options: ['Civil rights leader', 'President', 'Inventor', 'Scientist'], correct: 0 },
    { text: 'What is the Cold War?', options: ['US vs USSR', 'WWI', 'WWII', 'Vietnam War'], correct: 0 },
  ],
  economics: [
    { text: 'What is inflation?', options: ['Rise in prices', 'Fall in prices', 'Stable prices', 'No prices'], correct: 0 },
    { text: 'What is GDP?', options: ['Gross Domestic Product', 'Government Daily Profit', 'General Development Plan', 'Global Domestic Price'], correct: 0 },
    { text: 'What is demand?', options: ['Quantity wanted', 'Quantity supplied', 'Price', 'Income'], correct: 0 },
    { text: 'What is supply?', options: ['Quantity offered', 'Quantity demanded', 'Cost', 'Profit'], correct: 0 },
    { text: 'What is monopoly?', options: ['One seller', 'Many sellers', 'Two sellers', 'No sellers'], correct: 0 },
    { text: 'What is fiscal policy?', options: ['Government spending and taxes', 'Central bank money', 'Trade', 'Investment'], correct: 0 },
    { text: 'What is unemployment?', options: ['People without jobs', 'People with jobs', 'Inflation', 'Deflation'], correct: 0 },
    { text: 'What is exchange rate?', options: ['Value of currency', 'Interest rate', 'Tax rate', 'Growth rate'], correct: 0 },
    { text: 'What is budget?', options: ['Plan for income and expense', 'Savings', 'Loan', 'Investment'], correct: 0 },
    { text: 'What is capitalism?', options: ['Private ownership', 'Government ownership', 'Community ownership', 'No ownership'], correct: 0 },
  ],
  geography: [
    { text: 'What is the largest ocean?', options: ['Pacific', 'Atlantic', 'Indian', 'Arctic'], correct: 0 },
    { text: 'What is the capital of Japan?', options: ['Tokyo', 'Seoul', 'Beijing', 'Bangkok'], correct: 0 },
    { text: 'What is the longest river?', options: ['Nile', 'Amazon', 'Yangtze', 'Mississippi'], correct: 0 },
    { text: 'What is Mount Everest?', options: ['Highest mountain', 'Volcano', 'Island', 'Desert'], correct: 0 },
    { text: 'What is Sahara?', options: ['Desert', 'Ocean', 'Forest', 'Mountain'], correct: 0 },
    { text: 'What is equator?', options: ['Imaginary line', 'Pole', 'Meridian', 'Tropic'], correct: 0 },
    { text: 'What is Australia?', options: ['Continent', 'Country', 'Island', 'All'], correct: 3 },
    { text: 'What is the population of Earth?', options: ['8 billion', '7 billion', '9 billion', '6 billion'], correct: 0 },
    { text: 'What is Amazon?', options: ['Rainforest', 'Desert', 'Tundra', 'Grassland'], correct: 0 },
    { text: 'What is Arctic?', options: ['North Pole region', 'South Pole', 'Equator', 'Tropic'], correct: 0 },
  ],
  civic_education: [
    { text: 'What is citizenship?', options: ['Membership of a state', 'Voting', 'Paying taxes', 'Obeying laws'], correct: 0 },
    { text: 'What is democracy?', options: ['Rule by people', 'Rule by king', 'Rule by military', 'Rule by one'], correct: 0 },
    { text: 'What is human rights?', options: ['Basic freedoms', 'Laws', 'Duties', 'Privileges'], correct: 0 },
    { text: 'What is the Nigerian anthem?', options: ['Arise O Compatriots', 'God Save the King', 'Nkosi Sikelel', 'O Canada'], correct: 0 },
    { text: 'What is rule of law?', options: ['Everyone equal under law', 'Law above all', 'Government above law', 'Citizens above law'], correct: 0 },
    { text: 'What is voting age in Nigeria?', options: ['18', '16', '21', '15'], correct: 0 },
    { text: 'What is corruption?', options: ['Abuse of power', 'Honesty', 'Transparency', 'Integrity'], correct: 0 },
    { text: 'What is national flag?', options: ['Symbol of country', 'Currency', 'Anthem', 'Coat of arms'], correct: 0 },
    { text: 'What is peace?', options: ['Absence of conflict', 'War', 'Violence', 'Fight'], correct: 0 },
    { text: 'What is tolerance?', options: ['Accepting differences', 'Hate', 'Discrimination', 'Bias'], correct: 0 },
  ],
  crs: [
    { text: 'Who is Jesus?', options: ['Son of God', 'Prophet', 'King', 'Teacher'], correct: 0 },
    { text: 'What is the Bible?', options: ['Holy book', 'Novel', 'History book', 'Science book'], correct: 0 },
    { text: 'What is the first book of Bible?', options: ['Genesis', 'Matthew', 'Exodus', 'Revelation'], correct: 0 },
    { text: 'What is the Ten Commandments?', options: ['Laws from God', 'Stories', 'Prayers', 'Songs'], correct: 0 },
    { text: 'Who is Moses?', options: ['Led Israelites', 'King of Egypt', 'Prophet in Islam', 'Apostle'], correct: 0 },
    { text: 'What is resurrection?', options: ['Rising from dead', 'Birth', 'Death', 'Baptism'], correct: 0 },
    { text: 'What is Christmas?', options: ['Birth of Jesus', 'Death of Jesus', 'Resurrection', 'Pentecost'], correct: 0 },
    { text: 'What is Easter?', options: ['Resurrection of Jesus', 'Birth', 'Ascension', 'Baptism'], correct: 0 },
    { text: 'What is prayer?', options: ['Communication with God', 'Eating', 'Sleeping', 'Working'], correct: 0 },
    { text: 'What is faith?', options: ['Belief in God', 'Doubt', 'Fear', 'Anger'], correct: 0 },
  ],
  irs: [
    { text: 'Who is Muhammad?', options: ['Prophet of Islam', 'King', 'Apostle', 'Teacher'], correct: 0 },
    { text: 'What is the Quran?', options: ['Holy book of Islam', 'Bible', 'Torah', 'Veda'], correct: 0 },
    { text: 'What is Ramadan?', options: ['Fasting month', 'Festival', 'Prayer', 'Pilgrimage'], correct: 0 },
    { text: 'What is Hajj?', options: ['Pilgrimage to Mecca', 'Fasting', 'Prayer', 'Charity'], correct: 0 },
    { text: 'What is Zakat?', options: ['Charity', 'Fasting', 'Prayer', 'Pilgrimage'], correct: 0 },
    { text: 'What is Salah?', options: ['Prayer', 'Fasting', 'Charity', 'Pilgrimage'], correct: 0 },
    { text: 'What is Eid al-Fitr?', options: ['End of Ramadan', 'Birth of Prophet', 'Sacrifice', 'New year'], correct: 0 },
    { text: 'What is the first pillar of Islam?', options: ['Shahada', 'Salah', 'Zakat', 'Sawm'], correct: 0 },
    { text: 'What is Kaaba?', options: ['Holy site in Mecca', 'Mosque', 'Book', 'Prophet'], correct: 0 },
    { text: 'What is Jihad?', options: ['Struggle', 'War', 'Peace', 'Prayer'], correct: 0 },
  ],
  commerce: [
    { text: 'What is trade?', options: ['Exchange of goods', 'Manufacturing', 'Farming', 'Mining'], correct: 0 },
    { text: 'What is marketing?', options: ['Promoting products', 'Production', 'Finance', 'HR'], correct: 0 },
    { text: 'What is a company?', options: ['Business entity', 'Person', 'Government', 'School'], correct: 0 },
    { text: 'What is profit?', options: ['Revenue minus cost', 'Cost minus revenue', 'Revenue', 'Cost'], correct: 0 },
    { text: 'What is a market?', options: ['Place for buying/selling', 'Product', 'Service', 'Money'], correct: 0 },
    { text: 'What is advertising?', options: ['Promoting products', 'Selling', 'Buying', 'Transporting'], correct: 0 },
    { text: 'What is insurance?', options: ['Risk protection', 'Loan', 'Investment', 'Savings'], correct: 0 },
    { text: 'What is bank?', options: ['Financial institution', 'School', 'Hospital', 'Market'], correct: 0 },
    { text: 'What is entrepreneurship?', options: ['Starting business', 'Working', 'Studying', 'Farming'], correct: 0 },
    { text: 'What is capital?', options: ['Money for business', 'Labor', 'Land', 'Product'], correct: 0 },
  ],
  accounting: [
    { text: 'What is debit?', options: ['Left side', 'Right side', 'Balance', 'Profit'], correct: 0 },
    { text: 'What is credit?', options: ['Right side', 'Left side', 'Loss', 'Asset'], correct: 0 },
    { text: 'What is balance sheet?', options: ['Financial position', 'Income', 'Cash flow', 'Budget'], correct: 0 },
    { text: 'What is journal?', options: ['Book of original entry', 'Ledger', 'Trial balance', 'Statement'], correct: 0 },
    { text: 'What is asset?', options: ['Owned by business', 'Owed by business', 'Income', 'Expense'], correct: 0 },
    { text: 'What is liability?', options: ['Owed by business', 'Owned', 'Profit', 'Loss'], correct: 0 },
    { text: 'What is double entry?', options: ['Debit and credit', 'Single entry', 'Triple entry', 'No entry'], correct: 0 },
    { text: 'What is depreciation?', options: ['Reduction in asset value', 'Increase', 'Profit', 'Loss'], correct: 0 },
    { text: 'What is ledger?', options: ['Book of accounts', 'Journal', 'Trial', 'Balance'], correct: 0 },
    { text: 'What is trial balance?', options: ['List of balances', 'Income statement', 'Cash book', 'Bank statement'], correct: 0 },
  ],
  fine_arts: [
    { text: 'What is primary color?', options: ['Red, blue, yellow', 'Green, orange, purple', 'Black, white', 'Brown, gray'], correct: 0 },
    { text: 'What is sculpture?', options: ['3D art', 'Painting', 'Drawing', 'Music'], correct: 0 },
    { text: 'Who painted Mona Lisa?', options: ['Da Vinci', 'Picasso', 'Van Gogh', 'Monet'], correct: 0 },
    { text: 'What is perspective?', options: ['Depth in art', 'Color', 'Shape', 'Texture'], correct: 0 },
    { text: 'What is abstract art?', options: ['Non-representational', 'Realistic', 'Portrait', 'Landscape'], correct: 0 },
    { text: 'What is canvas?', options: ['Surface for painting', 'Brush', 'Paint', 'Easel'], correct: 0 },
    { text: 'What is pottery?', options: ['Clay art', 'Metal art', 'Wood art', 'Glass art'], correct: 0 },
    { text: 'What is mosaic?', options: ['Tile art', 'Painting', 'Sculpture', 'Drawing'], correct: 0 },
    { text: 'What is impressionism?', options: ['Light and color', 'Realism', 'Abstract', 'Cubism'], correct: 0 },
    { text: 'What is portrait?', options: ['Person image', 'Landscape', 'Still life', 'Abstract'], correct: 0 },
  ],
  music: [
    { text: 'What is a note?', options: ['Sound with pitch', 'Rhythm', 'Harmony', 'Melody'], correct: 0 },
    { text: 'What is clef?', options: ['Symbol for pitch', 'Key', 'Time', 'Dynamics'], correct: 0 },
    { text: 'What is tempo?', options: ['Speed of music', 'Volume', 'Pitch', 'Rhythm'], correct: 0 },
    { text: 'What is chord?', options: ['Multiple notes', 'Single note', 'Beat', 'Bar'], correct: 0 },
    { text: 'What is scale?', options: ['Series of notes', 'Instrument', 'Song', 'Dance'], correct: 0 },
    { text: 'What is symphony?', options: ['Orchestral music', 'Solo', 'Duo', 'Quartet'], correct: 0 },
    { text: 'Who is Beethoven?', options: ['Composer', 'Painter', 'Writer', 'Scientist'], correct: 0 },
    { text: 'What is jazz?', options: ['Improvisation music', 'Classical', 'Rock', 'Pop'], correct: 0 },
    { text: 'What is rhythm?', options: ['Beat pattern', 'Melody', 'Harmony', 'Timbre'], correct: 0 },
    { text: 'What is opera?', options: ['Sung drama', 'Dance', 'Play', 'Poem'], correct: 0 },
  ],
  home_economics: [
    { text: 'What is nutrition?', options: ['Study of food', 'Cooking', 'Cleaning', 'Sewing'], correct: 0 },
    { text: 'What is a balanced diet?', options: ['All nutrients', 'Only carbs', 'Only proteins', 'Only fats'], correct: 0 },
    { text: 'What is sewing?', options: ['Making clothes', 'Cooking', 'Cleaning', 'Gardening'], correct: 0 },
    { text: 'What is hygiene?', options: ['Cleanliness', 'Exercise', 'Sleep', 'Study'], correct: 0 },
    { text: 'What is first aid?', options: ['Initial care', 'Surgery', 'Medicine', 'Therapy'], correct: 0 },
    { text: 'What is budgeting?', options: ['Planning expenses', 'Shopping', 'Cooking', 'Cleaning'], correct: 0 },
    { text: 'What is child care?', options: ['Raising children', 'Pet care', 'Plant care', 'Car care'], correct: 0 },
    { text: 'What is laundry?', options: ['Washing clothes', 'Ironing', 'Sewing', 'Dyeing'], correct: 0 },
    { text: 'What is cooking?', options: ['Preparing food', 'Eating', 'Shopping', 'Storing'], correct: 0 },
    { text: 'What is family planning?', options: ['Controlling birth', 'Marriage', 'Divorce', 'Adoption'], correct: 0 },
  ],
  french: [
    { text: 'What is "hello" in French?', options: ['Bonjour', 'Hello', 'Hola', 'Ciao'], correct: 0 },
    { text: 'What is "thank you" in French?', options: ['Merci', 'Gracias', 'Danke', 'Thanks'], correct: 0 },
    { text: 'What is "yes" in French?', options: ['Oui', 'Si', 'Ja', 'Yes'], correct: 0 },
    { text: 'What is "no" in French?', options: ['Non', 'No', 'Nein', 'Nein'], correct: 0 },
    { text: 'What is "one" in French?', options: ['Un', 'One', 'Uno', 'Eins'], correct: 0 },
    { text: 'What is "house" in French?', options: ['Maison', 'House', 'Casa', 'Haus'], correct: 0 },
    { text: 'What is "school" in French?', options: ['École', 'School', 'Escuela', 'Schule'], correct: 0 },
    { text: 'What is "friend" in French?', options: ['Ami', 'Friend', 'Amigo', 'Freund'], correct: 0 },
    { text: 'What is "book" in French?', options: ['Livre', 'Book', 'Libro', 'Buch'], correct: 0 },
    { text: 'What is "water" in French?', options: ['Eau', 'Water', 'Agua', 'Wasser'], correct: 0 },
  ],
  yoruba: [
    { text: 'What is "hello" in Yoruba?', options: ['E kaaro', 'Hello', 'Bawo ni', 'O daabo'], correct: 2 },
    { text: 'What is "thank you" in Yoruba?', options: ['E seun', 'O se', 'Mo dupe', 'All'], correct: 3 },
    { text: 'What is "yes" in Yoruba?', options: ['Bee ni', 'Bee ko', 'Rara', 'Oti'], correct: 0 },
    { text: 'What is "no" in Yoruba?', options: ['Bee ko', 'Bee ni', 'Oti', 'Rara'], correct: 0 },
    { text: 'What is "one" in Yoruba?', options: ['Okan', 'Eji', 'Eta', 'Erin'], correct: 0 },
    { text: 'What is "house" in Yoruba?', options: ['Ile', 'Oko', 'Oja', 'Ile-iwe'], correct: 0 },
    { text: 'What is "school" in Yoruba?', options: ['Ile-iwe', 'Ile', 'Oja', 'Oko'], correct: 0 },
    { text: 'What is "friend" in Yoruba?', options: ['Ore', 'Ebi', 'Omo', 'Eniyan'], correct: 0 },
    { text: 'What is "book" in Yoruba?', options: ['Iwe', 'Kini', 'Pen', 'Paper'], correct: 0 },
    { text: 'What is "water" in Yoruba?', options: ['Omi', 'Ogun', 'Eja', 'Iyo'], correct: 0 },
  ],
  igbo: [
    { text: 'What is "hello" in Igbo?', options: ['Nnoo', 'Hello', 'Kedu', 'Ka odi'], correct: 2 },
    { text: 'What is "thank you" in Igbo?', options: ['Daalu', 'Imeela', 'Ekele', 'All'], correct: 3 },
    { text: 'What is "yes" in Igbo?', options: ['Ee', 'Mba', 'O di', 'Ka'], correct: 0 },
    { text: 'What is "no" in Igbo?', options: ['Mba', 'Ee', 'Ka', 'O di'], correct: 0 },
    { text: 'What is "one" in Igbo?', options: ['Otu', 'Abuo', 'Ato', 'Ano'], correct: 0 },
    { text: 'What is "house" in Igbo?', options: ['Ulo', 'Ugbo', 'Ahia', 'Ulo akwukwo'], correct: 0 },
    { text: 'What is "school" in Igbo?', options: ['Ulo akwukwo', 'Ulo', 'Ahia', 'Ugbo'], correct: 0 },
    { text: 'What is "friend" in Igbo?', options: ['Enyi', 'Nne', 'Nwa', 'Madu'], correct: 0 },
    { text: 'What is "book" in Igbo?', options: ['Akwukwo', 'Aka', 'Mkpisi', 'Mpempe'], correct: 0 },
    { text: 'What is "water" in Igbo?', options: ['Mmiri', 'Oku', 'Azu', 'Nnu'], correct: 0 },
  ],
  hausa: [
    { text: 'What is "hello" in Hausa?', options: ['Sannu', 'Hello', 'Ina kwana', 'Barka da rana'], correct: 2 },
    { text: 'What is "thank you" in Hausa?', options: ['Na gode', 'Godiya', 'Nagode', 'All'], correct: 3 },
    { text: 'What is "yes" in Hausa?', options: ['Eh', 'A\'a', 'To', 'Da kyau'], correct: 0 },
    { text: 'What is "no" in Hausa?', options: ['A\'a', 'Eh', 'Da kyau', 'To'], correct: 0 },
    { text: 'What is "one" in Hausa?', options: ['Dayan', 'Biyu', 'Uku', 'Hudu'], correct: 0 },
    { text: 'What is "house" in Hausa?', options: ['Gida', 'Gona', 'Kasuwa', 'Makaranata'], correct: 0 },
    { text: 'What is "school" in Hausa?', options: ['Makaranata', 'Gida', 'Kasuwa', 'Gona'], correct: 0 },
    { text: 'What is "friend" in Hausa?', options: ['Aboki', 'Uba', 'Yaro', 'Mutum'], correct: 0 },
    { text: 'What is "book" in Hausa?', options: ['Littafi', 'Rubutu', 'Alkalami', 'Takarda'], correct: 0 },
    { text: 'What is "water" in Hausa?', options: ['Ruwa', 'Wuta', 'Kifi', 'Gishiri'], correct: 0 },
  ],
  // ... (keep existing for government, economics, etc.)
};

export default questionsPool;
